spring:
  application:
    name: ad-eureka

server:
  port: 13000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
  port: 13001
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:13002/eureka/,http://server3:13003/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 13002
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:13001/eureka/,http://server3:13003/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 13003
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:13001/eureka/,http://server2:13002/eureka/